DELIMITER //

DROP FUNCTION IF EXISTS My_fn//
CREATE FUNCTION My_fn()
RETURNS TEXT DETERMINISTIC
BEGIN
	IF(CURTIME() BETWEEN '06:00:00' AND '12:00:00') THEN
		RETURN 'Доброе утро';
	ELSEIF(CURTIME() BETWEEN '12:00:00' AND '18:00:00') THEN
		RETURN 'Добрый день';
	ELSEIF(CURTIME() BETWEEN '18:00:00' AND '00:00:00') THEN
		RETURN 'Добрый вечер';
	ELSE
		RETURN 'Доброй ночи';
	END IF;
END//
DELIMITER ;

SELECT My_fn();
