DROP DATABASE IF EXISTS example; 
CREATE DATABASE example;
USE example;
CREATE TABLE users (id INT UNSIGNED, name VARCHAR(255));
SELECT * FROM users;
DROP DATABASE IF EXISTS sample; 
CREATE DATABASE sample;